---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-microservice
  labels:
    app: go-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-microservice
  template:
    metadata:
      labels:
        app: go-microservice
    spec:
      containers:
      - name: microservice
        image: localhost/go-microservice:0.1.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: dbdata
          mountPath: /var/go-microservice/data
        ports:
        - containerPort: 8060
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: local-path-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: go-microservice
spec:
  selector:
    app: go-microservice
  ports:
    - protocol: TCP
      port: 8060
      targetPort: 8060